### ISSUE TITLE
Performe evaluation

### ISSUE THREAD

**Issue by achetz** [zitmen/thunderstorm#40]
Hi, I'm trying to compare one ground truth with the results I'm attaching and I got the error I'm attaching. Is there anyone that has any idea why it is not working?
Thanks for your support and your nice package.

Best,
Anna

[result.txt](https://github.com/zitmen/thunderstorm/files/339139/result.txt)

[groundTruthForThunder.txt](https://github.com/zitmen/thunderstorm/files/339140/groundTruthForThunder.txt)
[Error.txt](https://github.com/zitmen/thunderstorm/files/339141/Error.txt)

**Comment by zitmen** [comment]
There is no issue, it does work. If anything, you might want to change to encoding of the text file. It now contains couple bytes at the beginning of the file that shouldn't be there.
