### ISSUE TITLE
Bug in Normalized Gaussian reconstruction

### ISSUE THREAD

**Issue by cleterrier** [zitmen/thunderstorm#48]
ThunderSTORM (latest build from 07-27-16), latest Fiji (ImageJ 1.51f) under Java 8 (102) on OSX El Capitan (10.11.5).

I think there is a bug in the "Normalized Gaussian" reconstruction mode. When the "force" option for the lateral uncertainty is unchecked, the reconstruction is supposed to be made from the localization results "uncertainty_xy" value (on a per-localization basis). This is the case if the "Lateral Uncertainty" box contains a large value (larger than the typical uncertainties contained in the localizations results). However, if this box contains a small value (for example 1 nm), then it modifies the reconstruction **even if the "force" box is unchecked**. The resulting Gaussians aren't normalized anymore! I have the impression that it limits the plotting to 3*1 nm, but with the intensity of the larger gaussian (corresponding to the uncertainty_xy value found in the localization results).

Here is how to replicate:
- Download the attached Test.zip folder and unzip it:
[Test.zip](https://github.com/zitmen/thunderstorm/files/448220/Test.zip)
- Open the test macro _Test_Macro.ijm_ with ImageJ.
- Edit the line 4 (run("Import"...) by inserting the path to the test localizations results file _Test_TS.xls_ (tab-delimited text file) contained in the unzipped folder.
- Set the pixel size in "Plugins>ThunderSTORM>Camera setup" to 160 nm for proper results. 
- Run the macro.

The test file has two rows of five localizations with uncertainties of 4, 8, 16, 32 and 64 nm. You should obtain two reconstructions: both are with "force" unchecked, but one with "1.0" nm in the Lateral Uncertainty box (corresponding to the attached _Test_TS(001)_Rec.tif_), the other with "100" nm (corresponding to the attached _Test_TS(100)_Rec.tif_). The correct reconstruction is "Test_TS(100)_Rec":
![test_ts 100 _rec](https://cloud.githubusercontent.com/assets/1062283/18145645/63f07e22-6fcc-11e6-9d63-4ed6ed31f443.jpg)
whereas "Test_TS(001)_Rec" is wrong:
![test_ts 001 _rec](https://cloud.githubusercontent.com/assets/1062283/18145663/72593e04-6fcc-11e6-88dd-06e7129985a0.jpg)

As it is, having a small value in the "Lateral Uncertainty" box can generate completely wrong reconstructions, so I think it is a serious bug.

**Comment by zitmen** [comment]
This should be correct.
![fixed_gaussian_rendering](https://cloud.githubusercontent.com/assets/206394/18231822/1fe9a15a-72c3-11e6-923b-d07e2a15a4c5.png)
